"""Update Usuario table

Revision ID: c396719a5d2b
Revises: db5e32300e15
Create Date: 2025-01-12 17:23:07.666732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c396719a5d2b'
down_revision: Union[str, None] = 'db5e32300e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_superuser')
    # ### end Alembic commands ###
