"""Update Usuario table

Revision ID: fe5024e4b90a
Revises: c396719a5d2b
Create Date: 2025-01-12 18:05:57.095260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5024e4b90a'
down_revision: Union[str, None] = 'c396719a5d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###
